spring:
  config:
    activate:
      on-profile: oracle-cloud-19c
  datasource:
    username: rixon
    password: wappit-xaVpop-fimqi9
    url: jdbc:oracle:thin:@rixoracloud2023_high?TNS_ADMIN=/Users/rixonmathew/apps/oracle/db_cloud/Wallet_RIXORACLOUD2023
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 300000
      pool-name: oracle19c
      connection-test-query: select 1 from dual
      data-source-properties:
        "[v$session.program]": data-access-tests
      idle-timeout: 120000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 9799

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level:
      - org.hibernate.SQL: error

---

spring:
  config:
    activate:
      on-profile: oracle-cloud-19c-win
  datasource:
    username: rixon
    password: wappit-xaVpop-fimqi9
    url: jdbc:oracle:thin:@rixoracloud2023_high?TNS_ADMIN=C:\\Users\\rixon\\Wallet_RIXORACLOUD2023
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 300000
      pool-name: oracle19c-win
      connection-test-query: select 1 from dual
      data-source-properties:
        "[v$session.program]": data-access-tests
      idle-timeout: 120000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 9799

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level:
      - org.hibernate.SQL: error

---
