### Reactive H2 All Contracts
GET localhost:9596/contracts

### Oracle Get instruments local machine
GET http://localhost:9799/instruments

### Oracle Get instruments local machine
GET http://localhost:9799/instruments/8950

### Oralce Get Instrument stream
GET http://localhost:9799/instruments/stream


### Oracle Get instruments
GET http://rixm1mini:9799/instruments

### Oracle Get Single instrument
GET http://rixm1mini:9799/instruments/8950

### Get instance from m4max
GET http://rixm4max:9799/instruments/8965

